[package]
name = "dist-dec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.21.2"
rand = {version = "0.8.5"}
rand_chacha = "0.3.1"
sha2 = "0.10.8"

[dev-dependencies]
# serial_test = "*"